/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-07-15 11:10:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>AJAX based CRUD operations using jTable in Servlet and JSP</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Include one of jTable styles. -->\r\n");
      out.write("<link href=\"js/themes/metro/crimson/jtable.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"js/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Include jTable script file. -->\r\n");
      out.write("<script src=\"js/jquery-2.1.4.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/jquery-ui.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/jquery.jtable.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- script src=\"js/jquery-1.8.2.js\" type=\"text/javascript\"></script -->\r\n");
      out.write("<!-- script src=\"js/jquery-ui-1.10.3.custom.js\" type=\"text/javascript\"></script -->\r\n");
      out.write("<!-- script src=\"js/jquery.jtable.js\" type=\"text/javascript\"></script -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        $('#PersonTableContainer').jtable({\r\n");
      out.write("            title: 'Table of people',\r\n");
      out.write("            actions: {\r\n");
      out.write("                listAction: 'crud?action=list',\r\n");
      out.write("                createAction:'crud?action=create',\r\n");
      out.write("                updateAction: 'crud?action=update',\r\n");
      out.write("                deleteAction: 'crud?action=delete'\r\n");
      out.write("            },\r\n");
      out.write("            fields: {\r\n");
      out.write("                userid: {\r\n");
      out.write("                 title:'S.NO',\r\n");
      out.write("                    key: true,\r\n");
      out.write("                    list: true,\r\n");
      out.write("                    create:true\r\n");
      out.write("                },\r\n");
      out.write("                firstName: {\r\n");
      out.write("                    title: 'First Name',\r\n");
      out.write("                    width: '30%',\r\n");
      out.write("                    edit:false\r\n");
      out.write("                },\r\n");
      out.write("                lastName: {\r\n");
      out.write("                    title: 'Last Name',\r\n");
      out.write("                    width: '30%',\r\n");
      out.write("                    edit:true\r\n");
      out.write("                },\r\n");
      out.write("                email: {\r\n");
      out.write("                    title: 'Email',\r\n");
      out.write("                    width: '20%',\r\n");
      out.write("                    edit: true\r\n");
      out.write("                }                \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $('#PersonTableContainer').jtable('load');\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"width:60%;margin-right:20%;margin-left:20%;text-align:center;\">\r\n");
      out.write("<h1>AJAX based CRUD operations in Java Web Application using jquery jTable plugin</h1>\r\n");
      out.write("<h4>Demo Application, Tutorial at <a href=\"http://www.programming-free.com/2013/07/setup-load-data-jtable-jsp-servlet.html\">www.programming-free.com</a></h4>\r\n");
      out.write("<div id=\"PersonTableContainer\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
